# -*- coding: utf-8 -*-
"""Job Title Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sv10gV32WtXITQ96ijx7sMCweXUkZScG
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('df.csv')

df

df['Job Title']   #تنوع شغلی رو میبینید که ... داره فوران میکنه

df['Job Title'].value_counts()  #تعداد دفعات ظهور هر عنوان شغلی در ستون

df['Job Title'].value_counts(normalize=True)  #برای دریافت درصد هر عنوان شغلی از کل استفاده کنید.

df['Job Title'].value_counts(dropna=False) # برای شمارش مقادیر نان(خالی) (مفقود) نیز استفاده کنید. که خالی نداریم

set(df['Job Title']) #مجموعه ای از تمام عناوین شغلی منحصر به فرد در ستون جابتایتل را ایجاد می کند. به عبارت دیگر، این کد فقط یک بار نام هر شغل را در مجموعه قرار می دهد، حتی اگر آن شغل چندین بار در دیتافریم تکرار شده باشد.
#"منحصر به فرد" در این مورد به معنای تک تک و بدون تکرار است.

len(set(df['Job Title'])) #این کد ابتدا یک مجموعه از تمام عناوین شغلی منحصر به فرد در ستون جاب تایتل ایجاد می کند. سپس، تعداد عناصر در این مجموعه را شمارش می کند و عدد حاصل را به عنوان خروجی ارائه می دهد.
#len(): تابعی برای شمارش تعداد عناصر در یک مجموعه

df['Job Title'].str.contains('Engineer')

import matplotlib.pyplot as plt    #matplotlib.pyplot برای ایجاد نمودارها استفاده می شود.
import pandas as pd   #فراخوانی کتابخانه ها

# Read the Job Title column from the CSV file
df = pd.read_csv('df.csv', usecols=['Job Title'])

# Count the number of times each job title appears
job_titles = df['Job Title'].value_counts()   # شمارش تعداد دفعات هر عنوان شغلی

# Create a bar chart
plt.bar(job_titles.index, job_titles.values)  #ایجاد نمودار ستونی
plt.xlabel('Job Title')    #نظیم برچسب های محورها
plt.ylabel('Count')        #نظیم برچسب های محورها
  #ین خطوط برچسب های محور X و Y نمودار را تنظیم می کنند
# Show all job titles on the x-axis
plt.xticks(rotation=90)  # Rotate x-axis labels for better readability   #چرخش برچسب های محور X   این خط برچسب های محور X را به میزان 10 درجه می چرخاند تا خوانایی آنها بهتر شود.
plt.show()    #نمایش نمودار: